title: Comco 2023
big_title: Computational Conference 2023
email: comco@uni-osnabrueck.de
date: 9<sup>th</sup> - 10<sup>th</sup>, October, 2023
date1: 1<sup>st</sup> August 2023
date2: 31<sup>th</sup> August 2023
date3: 18<sup>th</sup> September 2023
date4: 7<sup>th</sup> September 2023

phone: 0541-9693359
mobile: 
keywords: conference
address: University Osnabrück Institue for Cognitive Science, Wachsbleiche 27, 49069 Osnabrück
description: >- 
about_hits: >-
    some text.
    <br />
    more text.
    <br />
    blah blah blah.
about_cse: >-
    hello world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings
theme: minima
plugins:
    - jekyll-feed
