title: nbp lab wiki
logo: /assets/img/logo.png
description: this is the nbp lab wiki page
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
disqus:
  shortname: https-nbplabwiki-github-io
permalink: pretty
plugins:
  - jekyll-pdf-embed