title: Comco 2023
big_title:
email: comco@uni-osnabrueck.de
date: 9<sup>th</sup> - 10<sup>th</sup>, October, 2023
date1: Beginning of August 2023
date2: 31<sup>th</sup> August 2023
date3: 18<sup>th</sup> September 2023

phone: 0541-9693359
mobile: 
keywords: conference
address: University Osnabrück Institue for Cognitive Science, Wachsbleiche 27, 49069 Osnabrück
description: >- 
about_hits: >-
    The Computational Cognition Conference 2023 is hosted by the Research Training Group (RTG)
    "Computational Cognition" at the University Osanbrück. With our conference program, we plan
    to cover a diverse array of cutting-edge research topics throughout (computational) cognitive
    science and provide a welcoming platform for discussions among researchers.

    <br />

    In the conference, our key area of focus will be the investigation of high-level cognition. While we
    have made significant progress in understanding the neural signals underlying basic sensorimotor and
    cognitive processes involved in reasoning, problem solving, spatial navigation, and language, the
    challenge of explaining how high-level cognition can emerge from low-level mechanisms remains an
    interesting puzzle in cognitive science.

    <br />

    Keynote speakers from diverse backgrounds including computational neuroscience, neurolinguistics,
    cognitive modeling, machine learning and deep learning will share their expertise and present
    groundbreaking research at the conference. By bringing together these interdisciplinary perspectives,
    we aim to foster collaboration and spark new ideas that will drive the field of computational cognition
    forward!
    
    <br />

    Stay tuned for more updates on the conference schedule, speakers, and submission guidelines. We look
    forward to welcoming you to the Computational Cognition Conference 2023!

about_cse: >-
    
    In our working group, we aim to understand how meaningful representations emerge from raw signal
    data and to model high-level cognition such as learning, interaction, spatial navigation and language.
    We employ various methods from eye-tracking experiments in virtual reality to computational models
    using deep neural networks and reinforcement learning.
    <br />

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings
theme: minima
plugins:
    - jekyll-feed
